name: totyssey

services:
  api:
    build:
      context: ./backend # location of the Dockerfile relative to the compose file
      # dockerfile: Dockerfile # the name of the Dockerfile
      target: development
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - totyssey
    # ports:
    #   - 4004:4004 # host port : port in container

  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
      targe: development
      args:
        VITE_API_URL: https://api.auth.localhost
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - totyssey
    # ports:
    #   - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80 # port for http
      - 443:443 # port for https
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - totyssey
    depends_on:
      - api
      - frontend

volumes:
  caddy_data:
  caddy_config:

networks:
  totyssey:
    driver: bridge
